server:
  adminMinThreads: 1
  adminMaxThreads: 64
  enableAdminVirtualThreads: false
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 8081

swagger:
  resourcePackage: com.kishan
  title: Orbit API
  description: Orbit API
  version: 1.0

crawlingConfiguration:
  maxDepth: 1